### ISSUE TITLE
README

### ISSUE THREAD

**Issue by HalfLeif** [Qthulu/shrdlite-course-project#29] opened 2015-05-27 13:07 UTC
Hello

I started working on the README. It is not yet complete but there is not so much left to write there. Perhaps you Björn can finish it and then notify us so we all can read it through. Currently the OLD readme is still in the directory but should be removed before handin.

**Comment by HalfLeif** [comment] 2015-05-28 09:22
I think only the following parts need to be filled in and we are good to go

### Interesting example utterances

xxx (how to run your project, and some interesting example utterances)

...
xxx (where in the code is the ambiguity stuff?)

**Comment by Plankton555** [comment] 2015-05-28 20:19
Leif, sorry for not fixing what you wrote in the description/first comment. I forgot to look at the issue tracker (until now).

We have some interesting example utterances, and when I tested them I couldn't think of any more that shows something that's not already shown. Might add some more, but din't think it will add anything "new" to what's already there.

Regarding where in the code there is ambiguity stuff, I think it's best if @jeffpolk230 can confirm it or not. The two files that are listed there right now are the ones in which I could find things that clearly handled ambiguity stuff.

Other than that, I think we have added everything that he listed in the mail. So I guess we should just read through it and make sure we don't want to add anything more there :)

**Comment by HalfLeif** [comment] 2015-05-29 12:45
Np Björn. I agree, when Jeff can confirm where in the code Ambiguity is handled, we can hand it in.

**Comment by jeffpolk230** [comment] 2015-05-29 12:48
Hej Leif and Bjorn

Thanks for the work on README. Ive patched the missing bit related to
ambiguity system. I apologize for previous emotional comment. Just felt a
bit depressed with misunderstanding within the group.
just pushed the latest README and confirmed on details.

we're ready for hand in

thanks again and great work

All the best with exam :)
Jeff

2015-05-28 22:19 GMT+02:00 Plankton555 notifications@github.com:

> Leif, sorry for not fixing what you wrote in the description/first
> comment. I forgot to look at the issue tracker (until now).
> 
> We have some interesting example utterances, and when I tested them I
> couldn't think of any more that shows something that's not already shown.
> Might add some more, but din't think it will add anything "new" to what's
> already there.
> 
> Regarding where in the code there is ambiguity stuff, I think it's best if
> @jeffpolk230 https://github.com/jeffpolk230 can confirm it or not. The
> two files that are listed there right now are the ones in which I could
> find things that clearly handled ambiguity stuff.
> 
> Other than that, I think we have added everything that he listed in the
> mail. So I guess we should just read through it and make sure we don't want
> to add anything more there :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Qthulu/shrdlite-course-project/issues/29#issuecomment-106584785
> .

## 

Jeff

**Comment by HalfLeif** [comment] 2015-05-29 12:48
Great! I noticed there is still one "TODO" in Shrdlite.ts, should we just remove it? There is also some commented code there we can probably remove, as cleaning? Otherwise, I vote for handin.

**Comment by jeffpolk230** [comment] 2015-05-29 12:52
Aha that's to be removed
Sorry I seem to pushed a stale version

On Friday, May 29, 2015, Leif Schelin notifications@github.com wrote:

> Great! I noticed there is still one "TODO" in Shrdlite.ts, should we just
> remove it? There is also some commented code there we can probably remove,
> as cleaning? Otherwise, I vote for handin.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Qthulu/shrdlite-course-project/issues/29#issuecomment-106794042
> .

## 

Jeff

**Comment by Plankton555** [comment] 2015-05-29 18:51
Ok, I removed the TODO comment now. In that case, I guess we just have to submit it via the pull request. I'll do it in one hour or so in case someone finds something more to be fixed :)

Thanks for all the work, and especially for having patience with me and my lack of time due to other courses :P It's been great working with you!

**Comment by Plankton555** [comment] 2015-05-29 20:36
I have now merged development into master and issued a pull request (https://github.com/AI-course-TIN172-DIT410/shrdlite-course-project/pull/38).

Good work everyone! :)

**Closed as completed by Plankton555** 2015-05-29 20:36 UTC
Labels: help wanted

**Comment by HalfLeif** [comment] 2015-05-29 20:38
Well done, as always a pleasure working with you both. Good luck with the exams!
